apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-ca
  labels:
    {{- include "local-ca.labels" . | nindent 4 }}
spec:
  isCA: true
  commonName: local-ca
  secretName: local-ca-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
